name: PROD CICCD

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: prod-agent
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up environment variables
        run: |
          echo "REACT_APP_API_ENDPOINT=${{ secrets.REACT_APP_API_ENDPOINT_PROD }}" > .env

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_PROD }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_ID .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_ID
          docker image rm $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_ID
          docker logout $ECR_REGISTRY
  deploy:
    needs: build
    runs-on: prod-seap-agent
    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME_PROD }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS using Helm
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_PROD }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GROUP: seap-frontend-prod
        run: |
          curl -s -O https://$GH_PAT@raw.githubusercontent.com/tcpdigital8130/platform/main/helm-charts/seap.tar.gz
          curl -s -O https://$GH_PAT@raw.githubusercontent.com/tcpdigital8130/platform/main/envs/prod/services/seap-frontend/prod-values.yaml
          tar -xvzf seap.tar.gz
          helm upgrade --install $GROUP ./seap \
            --namespace prod --create-namespace -f ./prod-values.yaml \
            --set image.repository=$ECR_REGISTRY/$ECR_REPOSITORY \
            --set image.tag=$GITHUB_RUN_ID

      - name: Clean up kubeconfig
        run: |
          rm -f $HOME/.kube/config